### ISSUE TITLE
如果有一个针对Minecraft插件的IDE就好了

### ISSUE THREAD

**Issue by NukedBart** [SakuraKoi/Minecraft-Idea2Plugin#3]
拖拽式代码，左侧侧边栏存储bukkit相关的东西，并且有一个备注，左侧边栏顶部要有一个搜索框，比如搜索(创建新指令)就可以弄出一个创建新指令的框架，把方法都写好并且把plugin.yml都关联好；右侧代码视图带一个代码视图和程序积木块视图和混合视图(把所有的代码用中文注释代替，并且只留出填写参数，变量，常量的位置)，拖拽相关方法到代码视图能自动把代码写好，并且可以自动生成程序积木块视图和混合视图，编辑其他视图时也实时转换其他视图；编译的时候因为java代码都转好了所以应该可以直接编译jar

**Comment by SakuraKoi** [comment]
http://pvpin.com/
请(无慈悲
