### ISSUE TITLE
请教一下您的后门

### ISSUE THREAD

**Issue by RimuruChan** [SakuraKoi/Minecraft-Idea2Plugin#5]
![image](https://user-images.githubusercontent.com/42002296/88519537-dccc5480-d024-11ea-9d92-e952662eeea2.png)

n年前发给稀饭的后门是不是删掉主类了←_←

**Comment by LittleQiu233** [comment]
整挺好!

**Comment by SakuraKoi** [comment]
不提供任何后门利用的技术支持
